# Generated by Django 3.2.16 on 2023-04-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_title', models.CharField(max_length=300)),
                ('qna_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=15)),
                ('qna_content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=15)),
                ('com_comment', models.CharField(max_length=3000)),
                ('qna_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
