# Generated by Django 3.2.16 on 2023-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('img_name', models.CharField(max_length=128)),
                ('img_file', models.ImageField(blank=True, upload_to='images/')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('threshold', models.BooleanField(default=False)),
            ],
        ),
    ]
